# Generated by Django 3.0.3 on 2020-02-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200224_0818'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treacher',
            table='TeacherRegister',
        ),
    ]
