# Generated by Django 3.0.3 on 2020-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200224_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='treacher',
            name='teaching_subjects2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
