# Generated by Django 3.0.3 on 2020-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.IntegerField(default=1)),
                ('first_name', models.CharField(default='first name', max_length=50)),
                ('last_name', models.CharField(default='last name', max_length=50)),
                ('address', models.IntegerField(default=0)),
                ('town', models.CharField(default='town', max_length=50)),
                ('county', models.CharField(default='county', max_length=50)),
                ('postal_code', models.IntegerField(default=0)),
                ('fname', models.CharField(default='fname', max_length=50)),
                ('lname', models.CharField(default='last name', max_length=50)),
                ('phone', models.IntegerField(default=1234567)),
            ],
            options={
                'db_table': 'StudentRegister',
            },
        ),
    ]
