# Generated by Django 3.0.3 on 2020-02-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
