# Generated by Django 3.0.3 on 2020-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='form',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='county',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
    ]
