# Generated by Django 3.0.3 on 2020-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200221_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='admno',
            field=models.IntegerField(default=1, verbose_name='Admission'),
        ),
    ]
