# Generated by Django 3.0.3 on 2020-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200221_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='admno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='formclass',
            field=models.CharField(choices=[('Form1', 'Form One'), ('Form2', 'Form Two'), ('Form3', 'Form Three'), ('Form4', 'Form Four')], default='', max_length=20),
        ),
    ]
